name: Setup development environment for trends.earth CLI
description: Install Python dependencies and configure development tools for the trends.earth CLI project

on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.0
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true

      - name: Install dependencies
        run: |
          poetry install --no-interaction
          poetry run pre-commit install

      - name: Verify installation
        run: |
          poetry run trends --help
          poetry run pytest --version
          poetry run ruff --version
          poetry run mypy --version